### ISSUE TITLE
Fullscreen videos?

### ISSUE THREAD

**Issue by Spontini** [advaith1/activities#10]
Is there a way to make videos fullscreen? This is as biggest as I can go
![image](https://user-images.githubusercontent.com/35429381/130365840-dc274fb9-beea-40a7-96fb-fbe7d373b663.png)

**Comment by pazurkota** [comment]
It look's you can't fullscreen the video

**Comment by advaith1** [comment]
yeah, it doesn't look like Discord/YouTube Together supports that
