### ISSUE TITLE
Open the list of choices for `activity` parameter to make self hosting possible

### ISSUE THREAD

**Issue by asdf1280** [advaith1/activities#13]
It's not possible to open a self hosted bot because other people do not have list of activities and its application IDs. Please write it down in README so that people can add slash command to their own bots.

**Comment by Torbikini** [comment]
Yeah, I'm curious as to how this works. How does an invite get created with a specific activity?

**Comment by asdf1280** [comment]
Actually, it's very simple and i even implemented with Discord.js. Here's a part of my code.
```ts
        const applications = [
            "755827207812677713",
            "773336526917861400",
            "814288819477020702",
            "755600276941176913",
            "832012774040141894"
        ]
                let voice = message.member!.voice.channel as Discord.VoiceChannel
                let invite = await voice.createInvite({
                    maxAge: 10,
                    maxUses: 1,
                    targetType: 2, // InviteTargetType.EMBEDDED_APPLICATION
                    targetApplication: applications[choice]
                })
```

**Comment by advaith1** [comment]
The command data is registered in Discord, it isn't part of the code, and self-hosting is not supported.

The invite creation request is in the code, it uses the application id specified when using the command:

https://github.com/advaith1/activities/blob/b8805b991abbfb9f65e183c194f4616626e93ddb/src/bot.ts#L46-L54

After using the command, you can click the "/activity" to see the ID of the application you selected; Discord and the bot just receive the ID from your client.

**Comment by Torbikini** [comment]
Thanks for the speedy response, that's pretty interesting, actually. Cool idea! How did you even find the IDs in the first place, if you don't mind me asking?

**Comment by asdf1280** [comment]
> Thanks for the speedy response, that's pretty interesting, actually. Cool idea! How did you even find the IDs in the first place, if you don't mind me asking?

I found it with the original bot and dev tools.

**Comment by advaith1** [comment]
from the client: https://h.inv.wtf/filalukudu.js

**Comment by Endy3032** [comment]
> > Thanks for the speedy response, that's pretty interesting, actually. Cool idea! How did you even find the IDs in the first place, if you don't mind me asking?
> 
> I found it with the original bot and dev tools.

If you dont mind me asking, how did you get the IDs with the devtools tho? I cant seem to find any of those IDs in the console. The hastebin link doesnt work anymore. Maybe thats not the place to find but a follow-up would be appreciated!

Edit: After reading about "clicking the activity command to see the id" then the ID is not a problem anymore, but adding them automatically is a thing that i really want to try to make
