### ISSUE TITLE
Activities bot broken ?

### ISSUE THREAD

**Issue by lenicyl** [advaith1/activities#14]
I sat down to watch some youtube today, and noticed that there is a new option called "youtube togethter (new)", i used it and the bot even gave the link for joining the thing, but it wont work. I even tried chess, betrayal.io and other cool stuff in the bot. 

However when i try using an alt account, it works but not on my main ?

**Comment by advaith1** [comment]
try copying the link the bot sent (right click > copy link), pasting and sending it as a new message, and then clicking the one you sent; that should give you a useful message

often this happens because the user is IP banned from the server, such as an alt being banned

**Comment by lenicyl** [comment]
> try copying the link the bot sent (right click > copy link), pasting and sending it as a new message, and then clicking the one you sent; that should give you a useful message
> 
> often this happens because the user is IP banned from the server, such as an alt being banned

Ill try this when i get home, also the "banned" thing doesnt make sense since i am the owner...
Anyway thanks for the help :)
