### ISSUE TITLE
An error occured: You are being rate limited.

### ISSUE THREAD

**Issue by BlueHairMinerBoy** [advaith1/activities#16]
getting "An error occured: You are being rate limited." when i try to do anything

**Comment by nubovik01** [comment]
f

**Comment by Kqpa** [comment]
That means that you've performed an action repeatedly. You have to wait a while before doing whatever you're trying to do again.

**Comment by advaith1** [comment]
this happens when too many people are trying to use Activities at once, just wait a bit and try again
