### ISSUE TITLE
Nothing happens when clicking on link

### ISSUE THREAD

**Issue by Ming-A** [advaith1/activities#17]
For some reason when i click on the 'Click to open ' link it works for others but for me it doesn't do anything

**Comment by chroxify** [comment]
What os are you on?

**Comment by advaith1** [comment]
this is usually caused by being at the server limit or being ip-banned from the server

to get an error message you can copy the link the bot sent, re-send it, and click the one you sent

**Comment by Ming-A** [comment]
> What os are you on?

windows 10 pro 21H1



> this is usually caused by being at the server limit or being ip-banned from the server
> 
> to get an error message you can copy the link the bot sent, re-send it, and click the one you sent

when I copy and paste the link it then click on it, it highlights the message link that I copied from

**Comment by advaith1** [comment]
sounds like you used the "copy message link" option, not the "copy link" option

**Comment by Giggitybyte** [comment]
It's not working on my guild either.

**Comment by advaith1** [comment]
what issue are you having?

**Comment by Ming-A** [comment]
> sounds like you used the "copy message link" option, not the "copy link" option

my bad, yep seems like its due to the server limit
![image](https://user-images.githubusercontent.com/41011175/133705686-10b0f823-be0b-4525-9e47-c5762a264ecf.png)

**Comment by Giggitybyte** [comment]
Nothing happens when clicking the link; all activities worked fine the other day.

**Comment by advaith1** [comment]
@Giggitybyte see my earlier comment https://github.com/advaith1/activities/issues/17#issuecomment-921304633

**Comment by Ming-A** [comment]
> > What os are you on?
> 
> windows 10 pro 21H1
> 
> > this is usually caused by being at the server limit or being ip-banned from the server
> > to get an error message you can copy the link the bot sent, re-send it, and click the one you sent
> 
> when I copy and paste the link it then click on it, it highlights the message link that I copied from

left some servers that I'm not active in and that fixed it, thanks a lot :)

**Comment by Giggitybyte** [comment]
Ah, I didn't realize it was simply a guild invite. Thanks.
