### ISSUE TITLE
Channel invites are infinite

### ISSUE THREAD

**Issue by taureanjoe** [advaith1/activities#18]
Invitations that the bot creates are infinite numbers and **doesn't expire**. Could you please modify the bot to make the invites to be temporary for a few minutes?
With the current  setup of your bot, channel invitations stay permanent unless removed manually. And  after quiet sometime i don't want a message to popup saying "Maximum number of invites to this server reached".

**Comment by leoodz** [comment]
haven't check but i think you can change it [here](https://github.com/advaith1/activities/blob/b8805b991abbfb9f65e183c194f4616626e93ddb/src/bot.ts#L46)
![image](https://user-images.githubusercontent.com/26497373/134186179-b56922c4-b849-447e-8731-bc9bcecfa679.png)

**Comment by SerenModz21** [comment]
u would modify the `max_age` in the body

**Comment by advaith1** [comment]
I'll be keeping the invites permanent. The bot is designed so the link it sends will continue working forever, and you won't have to run the command every time. Also, creating invites is strictly rate-limited so it's better to create fewer invites.

If you use a command multiple times, it'll just send the invite that already exists if there is one, so Activities should not meaningfully contribute to your server hitting an invite limit.
