### ISSUE TITLE
fix(channel): option preview

### ISSUE THREAD

**Issue by XynoxTheDev** [advaith1/activities#2]
While using the slash command, the channel argument shows the options of both voice and text however this can be filtered by removing text channels. Also, there can be a channel as an optional argument if a user is already connected to a voice channel where the bot has permission to `View Channel` and `Create Instant Invite`.

**Comment by advaith1** [comment]
> however this can be filtered by removing text channels

this is unfortunately not a feature Discord supports, of course when they add that i will use it

> there can be a channel as an optional argument if a user is already connected to a voice channel

this is an interesting idea, but the bot would have to be rewritten and hosted differently to be able to see the user's voice state, and I'm not planning on that

**Comment by advaith1** [comment]
Discord has added support for filtering to certain channel types, so now only voice channels are shown
