### ISSUE TITLE
Why does the bot show as invis?

### ISSUE THREAD

**Issue by ImNimboss** [advaith1/activities#20]
Is there a reason to keep the bot invisible? It just misleads some people

**Comment by advaith1** [comment]
The bot is not invisible.

Activities received interactions over HTTP, so it doesn't have to connect to Discord's WebSocket Gateway. Currently, "online" means you have an active gateway connection, so http-only bots display as offline. This includes Discord's official Pronoun Picker bot.

Discord plans to make working http-only bots display as online in the future.

![AD548089-836B-44F2-9A7F-D6E6B2DD2622](https://user-images.githubusercontent.com/11778454/134374788-5f103998-11f7-42f5-8fa1-4413b87690c9.jpeg)

**Comment by vaporvee** [comment]
it doesn't have to but is it still possible that it can? it just looks a bit weird as offline in the sidebar

**Comment by ImNimboss** [comment]
It can, but for that the bot would have to be (re)wrote to connect to the gateway
