### ISSUE TITLE
Bring back old youtube together

### ISSUE THREAD

**Issue by DeathGOD7** [advaith1/activities#22]
Please bring back old youtube together as the new "watch together" is bugged as if I give someone remote access then my playback is paused and is on loop. And if I solely control the playback then others are 10 - 12 seconds behind.

And also if you could link docs of these activities it would be great.
Thank you.

**Comment by advaith1** [comment]
Discord asked for the old version to be removed from the bot, as the new version replaced it and the old version isn't supported. If you're having issues with the new version, you can give feedback or get help at https://discord.gg/discordgameslab

Docs on creating the invite: https://discord.com/developers/docs/resources/channel#create-channel-invite

**Comment by DeathGOD7** [comment]
Ok..but do you have application id lists?
