### ISSUE TITLE
cant watch youtube together with my friends

### ISSUE THREAD

**Issue by andywithcatz** [advaith1/activities#23]
so i've done /activites (vc channel) watch together and when me and my friends join i cant or my friends view the videos i put
tried on my other new test servers, doesnt work

**Comment by advaith1** [comment]
make sure none of the people are set to Invisible and all of the people have Activity Status enabled

**Comment by andywithcatz** [comment]
update: they can see it now but its now only just a gray screen, but when i minimize it, i can see it perfectly

**Comment by Milo123459** [comment]
discord bug?

**Comment by advaith1** [comment]
If they also can't see it when using the rocket button in https://discord.gg/discordgameslab then they should report it in #watch-issues in that server.
