### ISSUE TITLE
Watch together is full of bugs unlike Old Youtube Together

### ISSUE THREAD

**Issue by taureanjoe** [advaith1/activities#24]
Previously when there was YouTube together (old)  and YouTube together (new), I preferred using YouTube together (old), since it showed me who was trampling with the remote and also the sync was working smoothly. The only feature that lacked there was the ability to prevent other from using it. Now after the latest update of your bot, YouTube together (old) has disappeared and only the watch together mode is available. Whereas the new update brought feature to  allow or disallow people from controlling with the video, the stream doesn't sync with the members of our channel. Each member of the channel views the video in different timestamps and for the people who doesn't have control over the remote has the video playing again from the start. I have also noticed video automatically getting skipped from the queue. The feature of getting a popup of who is joining the session and who is leaving and also whoever is controlling the remote was a good feature, which is currently not available. I say that the bot is currently obsolete and can't be made accordingly.

**Comment by advaith1** [comment]
Discord creates the activities, and they said to remove the old YouTube Together because the new Watch Together replaces it. To report issues to them, use #watch-issues in https://discord.gg/discordgameslab.

**Comment by taureanjoe** [comment]
Why don't you see if you can clear those bugs?

**Comment by advaith1** [comment]
I'm not a Discord dev, I can't change anything inside the activities, so you'll need to report it to the devs in that server
