### ISSUE TITLE
How to create the slash command with voice channel option?

### ISSUE THREAD

**Issue by ugggaaaBuggaaa** [advaith1/activities#25]
I was not able to find the type of option for voice channel

**Comment by skepiaa** [comment]
![image](https://user-images.githubusercontent.com/68767065/138579829-45119e62-b615-445a-aaa7-62195a3f9320.png)

**Comment by advaith1** [comment]
it's a `CHANNEL` option with `channel_types` (set to [`2]`)

https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure
