### ISSUE TITLE
YoutubeTogether Stuck at Loading on Discord Windows Client

### ISSUE THREAD

**Issue by ZuherLaith** [advaith1/activities#3]
Below are the Activities that I tried:
1- Youtube Together: It just simply sits at Youtube Infinite Loading until the activity stops.
2- Betrayal.io: really slow loading until 50% and it stops.
3- Fishington.io: same result as Betrayal.io.
4- Poker Night: basically the only thing that's working fine.
When I go on Discord "In Browser Same Account", All the Activities works great as they should.

So why is Discord Windows client javascript "inflicts maybe?" on the stable discord..
I tried to reinstall discord, re-authorize permissions, didn't work for me, but my friends have it working fine.

**Comment by Expensiveee** [comment]
I don't think that @advaith1 is reponsible of this he just made the bot and discord haven't even released this feature yet so....

**Comment by advaith1** [comment]
yeah, this is a Discord issue and has nothing to do with the bot. try in https://discord.gg/betrayal maybe? if you can reproduce the issue in that server you might be able to get help with it there.
