### ISSUE TITLE
How can I get the application id of these games?

### ISSUE THREAD

**Issue by SHUSTRIK-Milan** [advaith1/activities#32]
**Hey!**

I know questions like this have existed, but unfortunately, no matter how hard I tried to use the information inside them, nothing came up. I tried to repeat the code exactly as indicated in the examples, but nothing came of it. Maybe you can help me?

In general, I would like to try to recreate the functionality of your bot, but on my server. Is this possible, if so, what is required for this? Thanks in advance!

> I used data from this [question](https://github.com/advaith1/activities/issues/13)

**Comment by advaith1** [comment]
here's one list of application IDs: https://derpystuff.gitlab.io/webstorage/discord/activities/ids.json
