### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by McJojo22** [advaith1/activities#33]
APIChatInputApplicationCommandInteractionDataResolved | APIUserApplicationCommandInteractionDataResolved | APIMessageApplicationCommandInteractionDataResolved'.\n  Property 'channels' does not exist on type 'APIUserApplicationCommandInteractionDataResolved'."

**Comment by advaith1** [comment]
sounds like you installed a different version of discord-api-types, it should have automatically installed the one in package.json
