### ISSUE TITLE
Unable to load activity

### ISSUE THREAD

**Issue by Yoshi24517** [advaith1/activities#38]
Trying to load PokerNight, and the bot says "unable to start activity."

Looking in Console logs, it says it can't load the activity from the API, giving a Forbidden 403 error. Checking the rest of the games, none of them work either.

**Comment by advaith1** [comment]
can you send a screenshot of the error?

**Comment by Yoshi24517** [comment]
Error when starting the activity:
![image](https://user-images.githubusercontent.com/27709108/154826282-270947ed-84fe-4fcc-b365-ec32ab1a1bfd.png)

Error in console logs:
![image](https://user-images.githubusercontent.com/27709108/154826308-0f9f6b58-2c1f-4639-b152-1128645291c5.png)

**Comment by advaith1** [comment]
Is your server boosted to level 1?

Also, this error is from Discord, not from the bot.

The API response in the network tab might have more information.

**Comment by advaith1** [comment]
ok looks like this might be a permissions issue: do you have the Start Activities permission in the server?

**Comment by Yoshi24517** [comment]
It was working before, like a week ago, so I don’t think that was the issue, unless discord added a new permission within that last week.

**Comment by advaith1** [comment]
The Start Activities permission was not enforced properly until last week. If you do have the permission, can you check the API response in the network tab?

**Comment by Yoshi24517** [comment]
Seems to be a permission for me. When I had somebody give me perms to start activities, the bot worked fine. Seems to be fixed now, so all good!
