### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by TDekkerDev** [advaith1/activities#40]
![Knipsel](https://user-images.githubusercontent.com/46562812/154861847-c8f6f28a-9a53-4d54-8996-fcc1ac9f46ce.PNG)

**Comment by advaith1** [comment]
This error is coming from Discord, not the bot. Can you open the DevTools Network tab and look at the response to the api request when you try to open the activity?

**Comment by advaith1** [comment]
ok looks like this might be a permissions issue: do you have the Start Activities permission in the server?

**Comment by TDekkerDev** [comment]
> This error is coming from Discord, not the bot. Can you open the DevTools Network tab and look at the response to the api request when you try to open the activity?

how?

**Comment by TDekkerDev** [comment]
> ok looks like this might be a permissions issue: do you have the Start Activities permission in the server?

yes

**Comment by TDekkerDev** [comment]
![Knipsel](https://user-images.githubusercontent.com/46562812/154862597-2a49912d-da91-4864-8671-06bafd6a208f.PNG)

**Comment by advaith1** [comment]
Press ctrl+shift+i (cmd+option+i on Mac) to open devtools. Then go to the Network tab at the top. Click the link the bot sent and it should add 2 or 3 requests to the list: look for the red one. Click the red one and click the "Preview" tab.

**Comment by advaith1** [comment]
> ![Knipsel](https://user-images.githubusercontent.com/46562812/154862597-2a49912d-da91-4864-8671-06bafd6a208f.PNG)

ok then it looks like you don't have the permission.

**Comment by TDekkerDev** [comment]
![Knipsel](https://user-images.githubusercontent.com/46562812/154862698-974ba83b-c3f5-4501-be1d-37720b70a08b.PNG)

**Comment by TDekkerDev** [comment]
> > ![Knipsel](https://user-images.githubusercontent.com/46562812/154862597-2a49912d-da91-4864-8671-06bafd6a208f.PNG)
> 
> ok then it looks like you don't have the permission.

i did not do a ting but after 5 min it works

**Comment by advaith1** [comment]
maybe a server admin edited the permissions then?

**Comment by TDekkerDev** [comment]
> maybe a server admin edited the permissions then?

no we did noting

**Comment by TDekkerDev** [comment]
when i make a new a heve to wacht and rejone

**Comment by TDekkerDev** [comment]
and how do it het the rockt icone net to screen share

**Comment by advaith1** [comment]
you cannot add the rocket button, you need to use the bot to start an activity. only certain servers have the rocket button.

**Comment by TDekkerDev** [comment]
okay how do i apply for the button

**Comment by advaith1** [comment]
You cannot apply, you can only get it randomly unless the server is run by Discord. Just use the bot.
