### ISSUE TITLE
"Not a valid choice" error on slash command

### ISSUE THREAD

**Issue by Theodorteo** [advaith1/activities#41]
Is this a discord or bot bug?
![0B479057-441A-4B6C-849F-1FD5E250FABB](https://user-images.githubusercontent.com/82102561/155850457-905549b2-d1c8-4bd4-a468-37ab15591d48.jpeg)

**Comment by advaith1** [comment]
You probably need to update the Discord app. Note that even when you can use the bot command, the mobile app doesn't support activities yet.
