### ISSUE TITLE
Request for new feature

### ISSUE THREAD

**Issue by Citr00n** [advaith1/activities#42]
Please add the possibility of using activities in the stands

**Comment by Justman10000** [comment]
Stands?

**Comment by Citr00n** [comment]
![image](https://user-images.githubusercontent.com/72319437/156023554-d707f63b-5265-47ca-a0a5-a9836e171792.png)
bad english, sorry

**Comment by advaith1** [comment]
Discord would need to add activities to stage channels, there's nothing I/the bot can do about that.

**Comment by advaith1** [comment]
in the API and maybe the client too

**Comment by Citr00n** [comment]
> ok
