### ISSUE TITLE
Click to open but not opening

### ISSUE THREAD

**Issue by EyeEnyx** [advaith1/activities#46]
When i click the hyperlink nothing happens.

https://user-images.githubusercontent.com/61381475/163137214-1a111fad-757b-40f5-9618-37972330aca1.mp4

**Comment by advaith1** [comment]
This is usually caused by your account being at its server limit or being ip-banned from the server you're trying to use the bot in (by having a banned alt account)

**Comment by duke4u2ply** [comment]
I have the same problem

**Comment by advaith1** [comment]
I already answered, my comment should help you resolve it.
