### ISSUE TITLE
It's not Working On mobile

### ISSUE THREAD

**Issue by ErYpTiC** [advaith1/activities#49]
It's just making the mobile be a text channel if iclik the inv in voice chat  ![Screenshot_20220607-232706_Discord.jpg](https://user-images.githubusercontent.com/105867746/172420139-aedbff58-5ca4-46dc-9e88-e289552a18ee.jpg)![Screenshot_20220607-232714_Discord.jpg](https://user-images.githubusercontent.com/105867746/172420156-703e0572-f303-4074-8752-b1d89f3dba59.jpg)![Screenshot_20220607-232720_Discord.jpg](https://user-images.githubusercontent.com/105867746/172420176-1a921b01-27c2-4651-8935-94bf777e8f29.jpg)![Screenshot_20220607-232736_Discord.jpg](https://user-images.githubusercontent.com/105867746/172420185-17eeee35-f757-4bc7-b44f-96119bdb09a7.jpg)

**Comment by advaith1** [comment]
activities are not supported on mobile yet; it should work once Discord adds support.
