### ISSUE TITLE
Nothing happens after clicking the link.

### ISSUE THREAD

**Issue by Blogames** [advaith1/activities#51]

**Comment by ManuelP22** [comment]
What link are you referring to? If this link https://get.activities.rocks/ works perfectly, this is the one that looks like get.activities.rocks. If not, then which link is having problems.

**Comment by ManuelP22** [comment]
> What link are you referring to? If this link https://get.activities.rocks/ works perfectly, this is the one that looks like get.activities.rocks. If not, then which link is having problems.


> _No description provided._

What link are you referring to? If this link https://get.activities.rocks/ works perfectly, this is the one that looks like get.activities.rocks. If not, then which link is having problems.

**Comment by ManuelP22** [comment]
> _No description provided._

What link are you referring to? If this link https://get.activities.rocks/ works perfectly, this is the one that looks like get.activities.rocks. If not, then which link is having problems.

**Comment by Soulivan71** [comment]
> _No description provided._

I'm having the same problem. 

https://github.com/advaith1/activities/issues/50

**Comment by Blogames** [comment]
Now, it works, idk what happend.
