### ISSUE TITLE
Activities won't start

### ISSUE THREAD

**Issue by Artanisky** [advaith1/activities#60]
As of today, they are not being started for activity. Is this a problem not only for me?

**Comment by suzu2469** [comment]
I can't start any activity on my server either.

**Comment by Merolone** [comment]
Also on my ds server no one type of activity start

**Comment by ipunjabigamer** [comment]
same on my server it wont start

**Comment by advaith1** [comment]
was a discord bug that has been fixed, ctrl+r and it should work
