### ISSUE TITLE
Bot isn't working

### ISSUE THREAD

**Issue by SomeRandomBot-I** [advaith1/activities#7]
The commands of the bot aren't showing...

**Comment by blendjam** [comment]
Yes the bot is currently offline :(

**Comment by Fayed06** [comment]
> Yes the bot is currently offline :(

hi , i'm just trying the bot and its work just fine even when the bot is offline



> The commands of the bot aren't showing...

I tried to use /activity to use youtube together and its work for me and my friend

**Comment by leoodz** [comment]
Try Cet Bot from top.gg. Great alternative I think

**Comment by ReaamNa** [comment]
you need to apply the slash commands in the text & images settings...
Even if its offline it still works.

**Comment by advaith1** [comment]
![image](https://user-images.githubusercontent.com/11778454/127072430-bd597e93-a4ed-4d06-b52e-ee9b381e2ec7.png)

---
Like any other bot, Activities' slash commands will not show if you have slash commands explicitly disabled in your User Settings.

![image](https://user-images.githubusercontent.com/11778454/127072501-402af57b-b0e3-425b-b20e-7f67f7d9e159.png)
